// src/components/ui/dicebear-avatar.tsx
import { cn } from "@/lib/utils";

/** DiceBear "adventurer" default avatar — seeded by name/email so it's stable per user. */
export function DiceBearAvatar({
  seed,
  size = 28,
  className,
  alt = "",
}: {
  seed: string;
  size?: number;
  className?: string;
  alt?: string;
}) {
  const safeSeed = encodeURIComponent((seed || "anonymous").trim().toLowerCase());
  const src = `https://api.dicebear.com/9.x/adventurer/svg?seed=${safeSeed}&backgroundType=gradientLinear&radius=50`;
  return (
    <img
      src={src}
      alt={alt}
      width={size}
      height={size}
      loading="lazy"
      className={cn("rounded-full bg-surface-2 object-cover shrink-0", className)}
      style={{ width: size, height: size }}
    />
  );
}

// resources/js/components/ui/DiceBearAvatar.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(
  defineProps<{
    seed: string;
    size?: number;
    src?: string | null;
    alt?: string;
  }>(),
  { size: 28, src: null, alt: "" },
);

const avatarUrl = computed(() => {
  if (props.src) return props.src;
  const seed = encodeURIComponent((props.seed || "anonymous").trim().toLowerCase());
  return `https://api.dicebear.com/9.x/adventurer/svg?seed=${seed}&backgroundType=gradientLinear&radius=50`;
});
</script>

<template>
  <img
    :src="avatarUrl"
    :alt="alt"
    :width="size"
    :height="size"
    loading="lazy"
    decoding="async"
    class="shrink-0 rounded-full bg-surface-muted object-cover"
    :style="{ width: `${size}px`, height: `${size}px` }"
  />
</template>
