// src/components/ui/page-header.tsx
import { cn } from "@/lib/utils";
import type { ReactNode } from "react";

interface Props {
  title: string;
  description?: ReactNode;
  actions?: ReactNode;
  className?: string;
}

export function PageHeader({ title, description, actions, className }: Props) {
  return (
    <div className={cn("flex flex-wrap items-start justify-between gap-3 mb-4", className)}>
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">{title}</h1>
        {description && <p className="text-xs text-text-muted mt-1">{description}</p>}
      </div>
      {actions && <div className="flex items-center gap-2">{actions}</div>}
    </div>
  );
}

// resources/js/components/ui/PageHeader.vue
<script setup lang="ts">
import AppTour from "@/components/tour/AppTour.vue";

defineProps<{ title: string; description: string }>();
</script>
<template>
  <header class="mb-4 flex flex-wrap items-start justify-between gap-3" data-tour="page-header">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">{{ title }}</h1>
      <p class="mt-1 text-sm text-text-muted">{{ description }}</p>
    </div>
    <div class="flex gap-2">
      <AppTour />
      <slot name="actions" />
    </div>
  </header>
</template>
