// src/routes/student.notifications.tsx
import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/ui/page-header";
import { Btn } from "@/components/ui/btn";
import { ListSkeleton } from "@/components/ui/skeletons";
import { useNotifications, useMarkNotificationRead } from "@/hooks/queries";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/student/notifications")({
  component: () => {
    const { data: items = [], isLoading } = useNotifications();
    const mark = useMarkNotificationRead();
    const toneMap: Record<string, string> = {
      info: "bg-info", success: "bg-success", warning: "bg-warning", danger: "bg-danger",
    };
    return (
      <div>
        <PageHeader title="Notifications" actions={<Btn variant="outline" onClick={() => mark.mutate("all")}>Mark all read</Btn>} />
        {isLoading ? (
          <ListSkeleton rows={5} />
        ) : items.length === 0 ? (
          <p className="text-sm text-text-muted py-10 text-center">No notifications.</p>
        ) : (
          <ul className="space-y-2">
            {items.map((n) => (
              <li key={n.id} className={cn("rounded-lg border bg-surface p-3 flex gap-3", !n.read && "border-primary/30 bg-primary-soft/20")}>
                <div className={cn("h-2 w-2 rounded-full mt-2 shrink-0", toneMap[n.type])} />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-sm font-medium">{n.title}</p>
                    <span className="text-micro text-text-soft">{new Date(n.created_at).toLocaleString()}</span>
                  </div>
                  <p className="text-xs text-text-muted">{n.body}</p>
                </div>
                {!n.read && <button onClick={() => mark.mutate(n.id)} className="text-micro text-primary hover:underline self-start">Mark read</button>}
              </li>
            ))}
          </ul>
        )}
      </div>
    );
  },
});

// frontend/src/modules/notifications/StudentNotifications.vue
<script setup lang="ts">
import { useNotificationChannel } from "@/composables/useEcho";
import { useNotificationList, useMarkNotificationRead, useMarkAllNotificationsRead } from "@/composables/useNotifications";
import { toast } from "@/composables/useToast";
import PageHeader from "@/components/ui/PageHeader.vue";
import ListSkeleton from "@/components/ui/ListSkeleton.vue";
import EmptyState from "@/components/ui/EmptyState.vue";

const { items, query: notificationsQuery } = useNotificationList();
const markReadMutation = useMarkNotificationRead();
const markAllMutation = useMarkAllNotificationsRead();

useNotificationChannel((payload) => {
  toast.info(payload.title, { description: payload.body });
});

const tones: Record<string, string> = {
  info: "bg-info",
  success: "bg-success",
  warning: "bg-warning",
  danger: "bg-danger",
  window_opened: "bg-success",
  window_closed: "bg-warning",
  deadline_extended: "bg-info",
};
</script>

<template>
  <div>
    <PageHeader
      title="Notifications"
      description="Account activity, validation updates, and reminders."
    >
      <template #actions>
        <button
          class="h-9 rounded-md border px-3 text-xs disabled:opacity-50"
          :disabled="markAllMutation.isPending.value || !items.some((item) => !item.read)"
          @click="markAllMutation.mutate()"
        >
          Mark all read
        </button>
      </template>
    </PageHeader>

    <ListSkeleton v-if="notificationsQuery.isLoading.value" :rows="5" />
    <EmptyState
      v-else-if="notificationsQuery.isError.value"
      variant="error"
      title="Couldn't load notifications"
      :hint="
        notificationsQuery.error.value instanceof Error
          ? notificationsQuery.error.value.message
          : 'Unable to load notifications.'
      "
      @retry="notificationsQuery.refetch()"
    />
    <ul v-else class="space-y-2">
      <li
        v-for="item in items"
        :key="item.id"
        :class="[
          'flex gap-3 rounded-lg border bg-surface p-3',
          !item.read && 'border-primary/30 bg-primary-soft/20',
        ]"
      >
        <i :class="['mt-2 h-2 w-2 shrink-0 rounded-full', tones[item.type] || 'bg-info']" />
        <div class="min-w-0 flex-1">
          <div class="flex justify-between gap-2">
            <p class="text-sm font-medium">{{ item.title }}</p>
            <span class="text-micro text-text-soft">{{ item.time }}</span>
          </div>
          <p class="text-xs text-text-muted">{{ item.body }}</p>
        </div>
        <button
          v-if="!item.read"
          class="self-start text-micro text-primary"
          @click="markReadMutation.mutate(item.id)"
        >
          Mark read
        </button>
      </li>
      <li v-if="!items.length">
        <EmptyState title="No notifications yet" hint="Batch window updates will appear here." />
      </li>
    </ul>
  </div>
</template>
