// apps/react-mock/src/components/ui/page-header.tsx
import { cn } from "@/lib/utils";
import type { ReactNode } from "react";
import { HelpButton } from "@/components/tour/help-button";

interface Props {
  title: string;
  description?: ReactNode;
  actions?: ReactNode;
  className?: string;
  /** Hide the auto tour help button on this page (default: shown when a tour exists). */
  hideTour?: boolean;
}

export function PageHeader({ title, description, actions, className, hideTour }: Props) {
  return (
    <div data-tour="page-header" className={cn("flex flex-wrap items-start justify-between gap-3 mb-4", className)}>
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">{title}</h1>
        {description && <p className="text-xs text-text-muted mt-1">{description}</p>}
      </div>
      {(actions || !hideTour) && (
        <div className="flex items-center gap-2">
          {!hideTour && <HelpButton />}
          {actions}
        </div>
      )}
    </div>
  );
}

// frontend/src/components/ui/PageHeader.vue
<script setup lang="ts">
import AppTour from "@/components/tour/AppTour.vue";
import { useI18n } from "vue-i18n";
import { translateKnownText } from "@/i18n/knownText";

defineProps<{ title: string; description: string }>();
const { t } = useI18n();
</script>
<template>
  <header class="mb-4 flex flex-wrap items-start justify-between gap-3" data-tour="page-header">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">{{ translateKnownText(t, title) }}</h1>
      <p class="mt-1 text-sm text-text-muted">{{ translateKnownText(t, description) }}</p>
    </div>
    <div class="flex gap-2">
      <AppTour />
      <slot name="actions" />
    </div>
  </header>
</template>
