// src/routes/student.settings.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { IconLock, IconHistory, IconCheck, IconDeviceLaptop } from "@tabler/icons-react";
import { PageHeader } from "@/components/ui/page-header";
import { ChartCard } from "@/components/ui/chart-card";
import { FormField, TextInput } from "@/components/ui/form-field";
import { Btn } from "@/components/ui/btn";
import { supabase } from "@/integrations/supabase/client";
import { useAuthStore } from "@/stores/authStore";

export const Route = createFileRoute("/student/settings")({
  component: StudentSettings,
});

function StudentSettings() {
  const userId = useAuthStore((s) => s.userId);
  const [current, setCurrent] = useState("");
  const [next, setNext] = useState("");
  const [confirm, setConfirm] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [ok, setOk] = useState<string | null>(null);

  const events = useQuery({
    queryKey: ["login_events", userId],
    enabled: !!userId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("login_events")
        .select("id, signed_in_at, ip_address, user_agent")
        .order("signed_in_at", { ascending: false })
        .limit(25);
      if (error) throw error;
      return data ?? [];
    },
  });

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setErr(null); setOk(null);
    if (next.length < 8) { setErr("New password must be at least 8 characters."); return; }
    if (next !== confirm) { setErr("Passwords do not match."); return; }
    setBusy(true);
    // Reauthenticate by attempting a sign-in with current password
    const { data: u } = await supabase.auth.getUser();
    const email = u.user?.email;
    if (!email) { setBusy(false); setErr("No user session."); return; }
    const { error: reauthErr } = await supabase.auth.signInWithPassword({ email, password: current });
    if (reauthErr) { setBusy(false); setErr("Current password is incorrect."); return; }
    const { error } = await supabase.auth.updateUser({ password: next });
    setBusy(false);
    if (error) { setErr(error.message); return; }
    setOk("Password updated successfully.");
    setCurrent(""); setNext(""); setConfirm("");
  }

  function deviceLabel(ua: string | null) {
    if (!ua) return "Unknown device";
    if (/iPhone|iPad/.test(ua)) return "iOS device";
    if (/Android/.test(ua)) return "Android device";
    if (/Mac OS X/.test(ua)) return "Mac";
    if (/Windows/.test(ua)) return "Windows PC";
    if (/Linux/.test(ua)) return "Linux";
    return "Browser";
  }

  return (
    <div>
      <PageHeader title="Settings" description="Manage your password and review recent sign-in activity." />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
        <ChartCard title="Change Password">
          <form onSubmit={submit} className="space-y-3">
            <FormField label="Current password" required>
              <TextInput type="password" value={current} onChange={(e) => setCurrent(e.target.value)} placeholder="••••••••" />
            </FormField>
            <FormField label="New password" required helper="At least 8 characters.">
              <TextInput type="password" value={next} onChange={(e) => setNext(e.target.value)} placeholder="••••••••" />
            </FormField>
            <FormField label="Confirm new password" required>
              <TextInput type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="••••••••" />
            </FormField>
            {err && <p className="text-xs text-danger">{err}</p>}
            {ok && <p className="text-xs text-success inline-flex items-center gap-1"><IconCheck size={12} /> {ok}</p>}
            <Btn variant="primary" type="submit" disabled={busy}>
              {busy ? "Updating…" : "Update password"}
            </Btn>
          </form>
        </ChartCard>

        <ChartCard title="Login Activity" icon={<IconHistory size={14} />}>
          {events.isLoading ? (
            <p className="text-xs text-text-muted">Loading…</p>
          ) : !events.data || events.data.length === 0 ? (
            <p className="text-xs text-text-muted">No login activity recorded yet.</p>
          ) : (
            <ul className="divide-y max-h-[420px] overflow-y-auto">
              {events.data.map((ev, idx) => (
                <li key={ev.id} className="flex items-start gap-3 py-2.5 text-sm">
                  <div className="h-8 w-8 rounded-md bg-surface-muted grid place-items-center text-text-muted shrink-0">
                    <IconDeviceLaptop size={14} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="font-medium truncate">{deviceLabel(ev.user_agent)}</p>
                      {idx === 0 && <span className="text-[10px] px-1.5 py-0.5 rounded bg-success-soft text-success font-medium">Current</span>}
                    </div>
                    <p className="text-[11px] text-text-muted">
                      {new Date(ev.signed_in_at).toLocaleString()}
                      {ev.ip_address ? ` · ${ev.ip_address}` : ""}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          )}
          <p className="mt-3 text-[10px] text-text-soft">Showing the last 25 sign-ins. Contact your office if you see activity you don't recognize.</p>
        </ChartCard>
      </div>
    </div>
  );
}

// resources/js/modules/settings/StudentSettings.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  IconCheck,
  IconDeviceLaptop,
  IconHistory,
  IconKey,
  IconLifebuoy,
  IconLogout,
  IconUser,
} from "@tabler/icons-vue";
import PageHeader from "@/components/ui/PageHeader.vue";
import DiceBearAvatar from "@/components/ui/DiceBearAvatar.vue";

type Section = "profile" | "security" | "sessions";
const section = ref<Section>("profile");
const saved = ref(false);
const passwordUpdated = ref(false);
const nav = [
  ["profile", "Profile", "Personal information", IconUser],
  ["security", "Security", "Change password", IconKey],
  ["sessions", "Sessions", "Sign-in activity", IconHistory],
];
</script>

<template>
  <div>
    <PageHeader title="Settings" description="Manage your profile, password, and sign-in activity."
      ><template #actions
        ><RouterLink
          to="/login"
          class="inline-flex h-9 items-center gap-1.5 rounded-md px-3 text-xs hover:bg-surface-muted"
          ><IconLogout :size="14" />Sign out</RouterLink
        ></template
      ></PageHeader
    >
    <div class="grid gap-4 lg:grid-cols-[220px_1fr]">
      <nav class="h-fit rounded-lg border bg-surface p-2">
        <button
          v-for="item in nav"
          :key="item[0] as string"
          :class="[
            'mb-0.5 flex w-full items-start gap-2 rounded-md px-2.5 py-2 text-left',
            section === item[0] ? 'bg-sidebar-active text-[#f5e6c4]' : 'hover:bg-surface-muted',
          ]"
          @click="section = item[0] as Section"
        >
          <component :is="item[3]" :size="16" class="mt-0.5" /><span
            ><b class="block text-sm">{{ item[1] }}</b
            ><span class="text-micro opacity-80">{{ item[2] }}</span></span
          >
        </button>
      </nav>
      <main>
        <section v-if="section === 'profile'" class="rounded-lg border bg-surface">
          <h2 class="border-b px-4 py-3 text-sm font-semibold">Edit Profile</h2>
          <div class="grid gap-5 p-5 md:grid-cols-[auto_1fr]">
            <div>
              <DiceBearAvatar
                seed="mc.delacruz@tcc.edu.ph"
                :size="80"
                alt="Maria Clara Dela Cruz"
              /><button class="mt-2 w-full text-xs text-primary">Change avatar</button>
            </div>
            <form class="max-w-xl space-y-4" @submit.prevent="saved = true">
              <label class="block"
                ><span class="mb-1.5 block text-xs font-medium">Full name *</span
                ><input
                  value="Maria Clara Dela Cruz"
                  disabled
                  class="h-9 w-full rounded-md border bg-surface-muted px-3 text-sm text-text-muted"
                />
                <span class="mt-1 block text-micro text-text-muted">
                  Your name is based on the official masterlist and cannot be edited here.
                </span></label
              >
              <div class="rounded-lg border border-info/30 bg-info-soft p-3 text-xs">
                <p class="flex items-center gap-2 font-semibold text-info">
                  <IconLifebuoy :size="14" /> Name issue?
                </p>
                <p class="mt-1 text-text-muted">
                  Contact support or the UniFAST office if your name is misspelled or does not match
                  your official records.
                </p>
                <a
                  href="mailto:registrar@tcc.edu.ph?subject=Student%20name%20correction%20request"
                  class="mt-2 inline-flex rounded-md border bg-surface px-3 py-1.5 text-micro font-medium text-primary"
                >
                  Contact support
                </a>
              </div>
              <label class="block"
                ><span class="mb-1.5 block text-xs font-medium">Email</span
                ><input
                  value="mc.delacruz@tcc.edu.ph"
                  disabled
                  class="h-9 w-full rounded-md border bg-surface-muted px-3 text-sm text-text-muted" /></label
              ><label class="block"
                ><span class="mb-1.5 block text-xs font-medium">Contact number</span
                ><input value="+63 917 123 4567" class="h-9 w-full rounded-md border px-3 text-sm"
              /></label>
              <p v-if="saved" class="inline-flex items-center gap-1 text-xs text-success">
                <IconCheck :size="12" />Profile updated.
              </p>
              <button class="block h-9 rounded-md bg-primary px-3 text-xs text-white">
                Save profile
              </button>
            </form>
          </div>
        </section>
        <section v-else-if="section === 'security'" class="rounded-lg border bg-surface">
          <h2 class="border-b px-4 py-3 text-sm font-semibold">Change Password</h2>
          <form class="max-w-xl space-y-4 p-4" @submit.prevent="passwordUpdated = true">
            <label
              v-for="label in ['Current password', 'New password', 'Confirm new password']"
              :key="label"
              class="block"
              ><span class="mb-1.5 block text-xs font-medium">{{ label }} *</span
              ><input
                type="password"
                placeholder="••••••••"
                class="h-9 w-full rounded-md border px-3"
            /></label>
            <div>
              <div class="flex justify-between text-micro">
                <span class="text-text-muted">Strength</span><span>Strong</span>
              </div>
              <div class="mt-1 h-1.5 rounded-full bg-surface-muted">
                <div class="h-full w-4/5 rounded-full bg-success" />
              </div>
            </div>
            <p v-if="passwordUpdated" class="inline-flex items-center gap-1 text-xs text-success">
              <IconCheck :size="12" />Password updated successfully.
            </p>
            <button class="block h-9 rounded-md bg-primary px-3 text-xs text-white">
              Update password
            </button>
          </form>
        </section>
        <template v-else
          ><section class="mb-3 rounded-lg border bg-surface p-4">
            <div class="flex gap-3">
              <span
                class="grid h-10 w-10 place-items-center rounded-md bg-primary-soft text-primary"
                ><IconDeviceLaptop :size="18"
              /></span>
              <div>
                <p class="text-sm font-medium">Current session · Windows PC</p>
                <p class="text-micro text-text-muted">Chrome · Manila, Philippines · Active now</p>
              </div>
            </div>
          </section>
          <section class="rounded-lg border bg-surface">
            <h2 class="border-b px-4 py-3 text-sm font-semibold">Login Activity</h2>
            <div class="divide-y px-4">
              <div
                v-for="event in [
                  ['Windows PC', 'Jul 12, 2026, 9:14 AM', '192.168.1.14'],
                  ['Android device', 'Jul 10, 2026, 6:35 PM', '192.168.1.22'],
                  ['Windows PC', 'Jul 8, 2026, 8:02 AM', '192.168.1.14'],
                ]"
                :key="event[1]"
                class="flex items-center gap-3 py-3"
              >
                <IconDeviceLaptop :size="16" class="text-text-muted" />
                <div>
                  <p class="text-sm font-medium">{{ event[0] }}</p>
                  <p class="text-micro text-text-muted">{{ event[1] }} · {{ event[2] }}</p>
                </div>
              </div>
            </div>
          </section></template
        >
      </main>
    </div>
  </div>
</template>
